
name: six_hit_challenge_final
description: Six Hit Challenge Final
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^4.0.0
flutter:
  uses-material-design: true
